-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 13:26:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema senasoft_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema senasoft_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `senasoft_bd` DEFAULT CHARACTER SET utf8 ;
USE `senasoft_bd` ;

-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_user` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_token` BIGINT NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  `carer of interest` VARCHAR(45) NULL,
  `education` CHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_forms` (
  `id` BIGINT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `start` DATE NOT NULL,
  `finish` DATE NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_form_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_form_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `senasoft_bd`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_questions` (
  `id` BIGINT NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `form_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_form1_idx` (`form_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_form1`
    FOREIGN KEY (`form_id`)
    REFERENCES `senasoft_bd`.`tb_forms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_results` (
  `id` BIGINT NOT NULL,
  `form_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_results_form1_idx` (`form_id` ASC) VISIBLE,
  CONSTRAINT `fk_results_form1`
    FOREIGN KEY (`form_id`)
    REFERENCES `senasoft_bd`.`tb_forms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_options_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_options_question` (
  `id` BIGINT NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `question_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_options_question_question1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_options_question_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `senasoft_bd`.`tb_questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_resources` (
  `id` BIGINT NOT NULL,
  `tipe` VARCHAR(45) NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resource_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_resource_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `senasoft_bd`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_goals` (
  `id` BIGINT NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `start` DATE NULL,
  `finish` DATE NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goals_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_goals_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `senasoft_bd`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_scores` (
  `id` BIGINT NOT NULL,
  `points` INT NOT NULL,
  `tb_forms_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_scores_tb_forms1_idx` (`tb_forms_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_scores_tb_forms1`
    FOREIGN KEY (`tb_forms_id`)
    REFERENCES `senasoft_bd`.`tb_forms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_statistics` (
  `id` BIGINT NOT NULL,
  `score_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estadistic_score1_idx` (`score_id` ASC) VISIBLE,
  INDEX `fk_estadistic_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_estadistic_score1`
    FOREIGN KEY (`score_id`)
    REFERENCES `senasoft_bd`.`tb_scores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estadistic_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `senasoft_bd`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_suports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_suports` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suport_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_suport_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `senasoft_bd`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_develop_rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_develop_rols` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `senasoft_bd`.`tb_user_has_develop_rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `senasoft_bd`.`tb_user_has_develop_rols` (
  `tb_user_id` BIGINT NOT NULL,
  `tb_DevRols_id` BIGINT NOT NULL,
  PRIMARY KEY (`tb_user_id`, `tb_DevRols_id`),
  INDEX `fk_tb_user_has_tb_DevRols_tb_DevRols1_idx` (`tb_DevRols_id` ASC) VISIBLE,
  INDEX `fk_tb_user_has_tb_DevRols_tb_user1_idx` (`tb_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_has_tb_DevRols_tb_user1`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `senasoft_bd`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_has_tb_DevRols_tb_DevRols1`
    FOREIGN KEY (`tb_DevRols_id`)
    REFERENCES `senasoft_bd`.`tb_develop_rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
