spring:
  datasource:
    url: jdbc:mysql://localhost:3307/senasoft_bd
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
