spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database_name
    username: root
    root: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  error:
    include-stacktrace: never
